'use client'

import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react'
import { Bar, BarChart, CartesianGrid, XAxis, YAxis } from 'recharts'
import { AlertTriangleIcon, CheckCircle2Icon, ClipboardCheckIcon, RefreshCwIcon, SearchIcon, ShieldAlertIcon } from 'lucide-react'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { ChartContainer, ChartTooltip, ChartTooltipContent, type ChartConfig } from '@/components/ui/chart'
import { Input } from '@/components/ui/input'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table'
import { cn } from '@/lib/utils'

type Inventory={warehouseId:string;productId:string;warehouseCode:string;sku:string;name:string;saleUnit:string;onHandQuantity:number;reservedQuantity:number;availableQuantity:number;stockCountActive:boolean}
type Reservation={orderId:string;customerCode:string;customerName:string;reservationId:string;remainingQuantity:number}
type Count={id:string;status:'counting'|'finalized'|'cancelled';warehouseId:string;productId:string;warehouseCode:string;sku:string;name:string;saleUnit:string;snapshotOnHandQuantity:number;snapshotReservedQuantity:number;countedQuantity:number|null;releasedReservationQuantity:number;reason:string;startedAt:string;startedBy:string;finalizedAt:string|null;finalizedBy:string|null;cancelledAt:string|null;cancelledBy:string|null;currentOnHandQuantity:number;currentReservedQuantity:number;reservations:Reservation[]}
const chartConfig={variance:{label:'실사 차이',color:'#2563eb'},released:{label:'예약 해제',color:'#f59e0b'}} satisfies ChartConfig
async function csrf(){const response=await fetch('/api/auth/csrf',{credentials:'same-origin'});if(!response.ok)throw new Error('보안 토큰을 준비하지 못했습니다.');return(await response.json() as {csrfToken:string}).csrfToken}

export default function StockCountsPage(){
 const[inventory,setInventory]=useState<Inventory[]>([]),[counts,setCounts]=useState<Count[]>([]),[selectedKey,setSelectedKey]=useState(''),[query,setQuery]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true)
 const load=useCallback(async()=>{setLoading(true);const[stockResponse,countResponse]=await Promise.all([fetch('/api/admin/inventory',{credentials:'same-origin'}),fetch('/api/admin/stock-counts',{credentials:'same-origin'})]);if(!stockResponse.ok||!countResponse.ok){setMessage('실사 작업 정보를 불러오지 못했습니다.');setLoading(false);return}const stocks=await stockResponse.json() as Inventory[],records=await countResponse.json() as Count[];setInventory(stocks);setCounts(records);const activeCount=records.find(item=>item.status==='counting'),defaultKey=activeCount?key(activeCount):(stocks[0]?key(stocks[0]):'');setSelectedKey(current=>stocks.some(item=>key(item)===current)?current:defaultKey);setMessage('');setLoading(false)},[])
 useEffect(()=>{void load()},[load])
 const visible=useMemo(()=>inventory.filter(item=>!query.trim()||`${item.warehouseCode} ${item.sku} ${item.name}`.toLowerCase().includes(query.trim().toLowerCase())),[inventory,query])
 useEffect(()=>{if(visible.length&&!visible.some(item=>key(item)===selectedKey))setSelectedKey(key(visible[0]))},[visible,selectedKey])
 const selected=inventory.find(item=>key(item)===selectedKey)??null,active=selected?counts.find(item=>item.status==='counting'&&item.warehouseId===selected.warehouseId&&item.productId===selected.productId)??null:null
 const completed=counts.filter(item=>item.status==='finalized'),released=completed.reduce((sum,item)=>sum+item.releasedReservationQuantity,0)
 async function command(path:string,payload:object){setBusy(true);setMessage('');try{const response=await fetch(path,{method:'POST',credentials:'same-origin',headers:{'content-type':'application/json','x-csrf-token':await csrf()},body:JSON.stringify({requestId:crypto.randomUUID(),...payload})});const result=await response.json().catch(()=>({})) as {message?:string};if(!response.ok)throw new Error(result.message??'실사 작업을 처리하지 못했습니다.');setMessage('실사 작업을 반영했습니다.');await load()}catch(error){setMessage(error instanceof Error?error.message:'실사 작업 중 오류가 발생했습니다.')}finally{setBusy(false)}}
 return <div className="space-y-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><h1 className="text-2xl font-semibold tracking-tight">재고 실사</h1><p className="mt-1 text-sm text-muted-foreground">SKU 이동을 보류하고 실측 수량과 예약 차이를 안전하게 조정합니다.</p></div><Button variant="outline" onClick={()=>void load()} disabled={loading}><RefreshCwIcon className={loading?'animate-spin':''}/>새로고침</Button></div>
 {message&&<div role="status" className="rounded-md border bg-muted/40 px-4 py-3 text-sm">{message}</div>}
 <section className="grid gap-3 sm:grid-cols-3"><Metric label="실사 진행" value={counts.filter(item=>item.status==='counting').length} icon={ShieldAlertIcon}/><Metric label="실사 확정" value={completed.length} icon={CheckCircle2Icon}/><Metric label="예약 해제" value={released} unit="개" icon={AlertTriangleIcon}/></section>
 <div className="grid items-start gap-4 xl:grid-cols-[360px_minmax(0,1fr)]"><Card className="xl:sticky xl:top-20"><CardHeader className="border-b"><CardTitle>실사 대상 SKU</CardTitle><CardDescription>보유·예약 수량과 현재 보류 상태를 확인합니다.</CardDescription><label className="relative mt-2"><SearchIcon className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground"/><Input className="pl-9" value={query} onChange={event=>setQuery(event.target.value)} placeholder="창고, SKU, 상품명 검색"/></label></CardHeader><CardContent className="max-h-[650px] overflow-y-auto p-0">{visible.map(item=><button type="button" key={key(item)} onClick={()=>setSelectedKey(key(item))} className={cn('w-full border-b px-4 py-3 text-left hover:bg-muted/50',selectedKey===key(item)&&'bg-muted')}><div className="flex items-start justify-between gap-2"><div><strong className="text-sm">{item.name}</strong><p className="mt-1 font-mono text-[11px] text-muted-foreground">{item.sku} · {item.warehouseCode}</p></div>{item.stockCountActive&&<Badge variant="outline" className="border-amber-300 bg-amber-50 text-amber-800">실사 중</Badge>}</div><div className="mt-3 grid grid-cols-3 gap-2 text-xs"><Quantity label="보유" value={item.onHandQuantity}/><Quantity label="예약" value={item.reservedQuantity}/><Quantity label="가용" value={item.availableQuantity}/></div></button>)}{!visible.length&&<p className="py-14 text-center text-sm text-muted-foreground">검색 결과가 없습니다.</p>}</CardContent></Card>
 {selected?<Card><CardHeader className="border-b"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="mb-2 flex items-center gap-2">{active?<Badge className="bg-amber-500">이동 보류</Badge>:<Badge variant="secondary">작업 가능</Badge>}<span className="font-mono text-xs text-muted-foreground">{selected.sku}</span></div><CardTitle>{selected.name}</CardTitle><CardDescription>{selected.warehouseCode} · {selected.saleUnit}</CardDescription></div><div className="grid grid-cols-3 gap-5 text-right"><Quantity label="보유" value={selected.onHandQuantity}/><Quantity label="예약" value={selected.reservedQuantity}/><Quantity label="가용" value={selected.availableQuantity}/></div></div></CardHeader><CardContent className="space-y-5">{active?<ActiveCount count={active} busy={busy} command={command}/>:<StartCount stock={selected} busy={busy} command={command}/>}</CardContent></Card>:<Card><CardContent className="grid min-h-72 place-items-center text-sm text-muted-foreground">실사할 SKU를 선택해 주세요.</CardContent></Card>}</div>
 <History counts={counts}/></div>
}

function StartCount({stock,busy,command}:{stock:Inventory;busy:boolean;command:(path:string,payload:object)=>Promise<void>}){return <form className="space-y-4" onSubmit={(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=new FormData(event.currentTarget);void command('/api/admin/stock-counts',{warehouseId:stock.warehouseId,productId:stock.productId,reason:form.get('reason')})}}><div className="rounded-lg border bg-muted/30 p-4"><strong className="flex items-center gap-2 text-sm"><ClipboardCheckIcon className="size-4"/>실사 시작 전 확인</strong><ul className="mt-2 space-y-1 text-xs text-muted-foreground"><li>이 SKU의 입고·예약·피킹·검수·출고·반품 복귀·일반 정정이 보류됩니다.</li><li>이미 피킹 또는 검수한 수량이 있으면 실사를 시작할 수 없습니다.</li><li>실측 부족 시 최신 주문 예약부터 부족 수량만큼 해제됩니다.</li></ul></div><label className="grid gap-2 text-sm font-medium">실사 사유<Input name="reason" maxLength={300} placeholder="예: 9월 정기 재고 실사" required/></label><div className="flex justify-end"><Button disabled={busy}><ShieldAlertIcon/>SKU 이동 보류 후 실사 시작</Button></div></form>}

function ActiveCount({count,busy,command}:{count:Count;busy:boolean;command:(path:string,payload:object)=>Promise<void>}){return <><div className="grid gap-2 sm:grid-cols-3"><Info label="실사 시작" value={new Date(count.startedAt).toLocaleString('ko-KR')}/><Info label="시작 보유" value={`${count.snapshotOnHandQuantity.toLocaleString('ko-KR')}개`}/><Info label="시작 예약" value={`${count.snapshotReservedQuantity.toLocaleString('ko-KR')}개`}/></div>{count.reservations.length>0&&<div className="rounded-lg border"><div className="border-b bg-muted/30 px-4 py-3"><strong className="text-sm">영향받는 예약</strong><p className="mt-0.5 text-xs text-muted-foreground">실측 수량이 예약보다 적으면 아래 목록의 최신 주문부터 해제됩니다.</p></div><div className="divide-y">{count.reservations.map(item=><div className="flex items-center justify-between gap-3 px-4 py-3 text-sm" key={item.reservationId}><div><strong>{item.customerName}</strong><p className="font-mono text-[11px] text-muted-foreground">{item.customerCode} · #{item.orderId.slice(0,8).toUpperCase()}</p></div><span className="font-semibold tabular-nums">{item.remainingQuantity}개</span></div>)}</div></div>}
 <form className="rounded-lg border border-blue-200 p-4" onSubmit={(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=new FormData(event.currentTarget);void command(`/api/admin/stock-counts/${count.id}/finalize`,{countedQuantity:Number(form.get('countedQuantity')),reason:form.get('reason')})}}><div><strong className="text-sm">실측 수량 확정</strong><p className="mt-1 text-xs text-muted-foreground">예약보다 부족하면 초과 예약을 해제하고 해당 주문을 미확보 상태로 전환합니다.</p></div><div className="mt-4 grid gap-3 sm:grid-cols-[180px_1fr_auto]"><label className="grid gap-1.5 text-xs font-medium">실측 정상 재고<Input name="countedQuantity" type="number" min="0" step="1" defaultValue={count.snapshotOnHandQuantity} required/></label><label className="grid gap-1.5 text-xs font-medium">확정 사유<Input name="reason" maxLength={300} placeholder="실측 결과와 차이 원인" required/></label><Button className="self-end" disabled={busy}>실사 확정</Button></div></form><form className="flex flex-col gap-3 rounded-lg border p-4 sm:flex-row sm:items-end" onSubmit={(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();void command(`/api/admin/stock-counts/${count.id}/cancel`,{reason:new FormData(event.currentTarget).get('reason')})}}><label className="grid flex-1 gap-1.5 text-xs font-medium">실사 취소 사유<Input name="reason" maxLength={300} placeholder="예: 대상 SKU 선택 오류" required/></label><Button variant="outline" disabled={busy}>보류 해제</Button></form></>}

function History({counts}:{counts:Count[]}){const closed=counts.filter(item=>item.status!=='counting'),data=closed.filter(item=>item.status==='finalized').slice(0,10).reverse().map(item=>({sku:item.sku,variance:(item.countedQuantity??item.snapshotOnHandQuantity)-item.snapshotOnHandQuantity,released:item.releasedReservationQuantity}));return <div className="grid gap-4 xl:grid-cols-[minmax(0,0.8fr)_minmax(0,1.2fr)]"><Card><CardHeader><CardTitle>최근 실사 차이</CardTitle><CardDescription>실측 증감과 예약 해제 수량을 비교합니다.</CardDescription></CardHeader><CardContent>{data.length?<ChartContainer config={chartConfig} className="h-56 w-full"><BarChart data={data} accessibilityLayer><CartesianGrid vertical={false}/><XAxis dataKey="sku"/><YAxis allowDecimals={false}/><ChartTooltip content={<ChartTooltipContent/>}/><Bar dataKey="variance" fill="var(--color-variance)" radius={3}/><Bar dataKey="released" fill="var(--color-released)" radius={3}/></BarChart></ChartContainer>:<p className="grid h-56 place-items-center text-sm text-muted-foreground">확정된 실사 기록이 없습니다.</p>}</CardContent></Card><Card><CardHeader><CardTitle>실사 이력</CardTitle><CardDescription>최근 시작·확정·취소 기록 {closed.length}건</CardDescription></CardHeader><CardContent className="p-0"><div className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>SKU</TableHead><TableHead>상태</TableHead><TableHead className="text-right">기준</TableHead><TableHead className="text-right">실측</TableHead><TableHead className="text-right">예약 해제</TableHead><TableHead>처리 시각</TableHead></TableRow></TableHeader><TableBody>{closed.map(item=><TableRow key={item.id}><TableCell><strong>{item.name}</strong><p className="font-mono text-[11px] text-muted-foreground">{item.sku}</p></TableCell><TableCell><Badge variant={item.status==='finalized'?'secondary':'outline'}>{item.status==='finalized'?'확정':'취소'}</Badge></TableCell><TableCell className="text-right tabular-nums">{item.snapshotOnHandQuantity}</TableCell><TableCell className="text-right tabular-nums">{item.countedQuantity??'-'}</TableCell><TableCell className="text-right tabular-nums">{item.releasedReservationQuantity}</TableCell><TableCell className="whitespace-nowrap text-xs">{new Date(item.finalizedAt??item.cancelledAt??item.startedAt).toLocaleString('ko-KR')}</TableCell></TableRow>)}{!closed.length&&<TableRow><TableCell colSpan={6} className="h-28 text-center text-muted-foreground">종료된 실사 기록이 없습니다.</TableCell></TableRow>}</TableBody></Table></div></CardContent></Card></div>}

const key=(item:Pick<Inventory,'warehouseId'|'productId'>)=>`${item.warehouseId}:${item.productId}`
function Metric({label,value,unit='건',icon:Icon}:{label:string;value:number;unit?:string;icon:typeof ShieldAlertIcon}){return <Card size="sm"><CardHeader className="grid grid-cols-[1fr_auto]"><CardDescription>{label}</CardDescription><span className="row-span-2 grid size-8 place-items-center rounded-md bg-muted"><Icon className="size-4"/></span><CardTitle className="text-2xl tabular-nums">{value.toLocaleString('ko-KR')} <span className="text-sm font-normal text-muted-foreground">{unit}</span></CardTitle></CardHeader></Card>}
function Quantity({label,value}:{label:string;value:number}){return <div><p className="text-muted-foreground">{label}</p><strong className="tabular-nums">{value.toLocaleString('ko-KR')}</strong></div>}
function Info({label,value}:{label:string;value:string}){return <div className="rounded-lg bg-muted/50 p-3"><p className="text-xs text-muted-foreground">{label}</p><strong className="mt-1 block text-sm">{value}</strong></div>}
