"use client"

import { FormEvent, useEffect, useState } from "react"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"

type Customer = { id: string; code: string; name: string }
type Detail = { id: string; status: string; supplyAmount: string; taxAmount: string; totalAmount: string; dueDate?: string | null; lineCount: number; lines?: { id: string; entryType: string; businessDate: string; sku: string; productName: string; supplyAmount: string; taxAmount: string; amount: string }[] }
const won = (amount: string) => `${Number(amount).toLocaleString("ko-KR")}원`
const selectClass = "h-9 rounded-md border border-input bg-transparent px-3 text-sm outline-none focus-visible:ring-2 focus-visible:ring-ring/50"
async function csrf() { return (await (await fetch("/api/auth/csrf", { credentials: "same-origin" })).json() as { csrfToken: string }).csrfToken }

export default function SettlementDraftsPage() {
  const [customers, setCustomers] = useState<Customer[]>([]), [customerId, setCustomerId] = useState(""), [period, setPeriod] = useState(new Date().toISOString().slice(0, 7)), [detail, setDetail] = useState<Detail | null>(null), [message, setMessage] = useState("")
  useEffect(() => { void (async () => { const response = await fetch("/api/admin/catalog", { credentials: "same-origin" }); if (response.ok) setCustomers((await response.json() as { customers: Customer[] }).customers); else setMessage("거래처 목록을 불러오지 못했습니다.") })() }, [])
  const create = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const response = await fetch("/api/admin/settlements", { method: "POST", credentials: "same-origin", headers: { "content-type": "application/json", "x-csrf-token": await csrf() }, body: JSON.stringify({ requestId: crypto.randomUUID(), customerId, period }) }); if (!response.ok) return setMessage("정산 초안을 만들지 못했습니다. 같은 거래처·정산월의 초안 여부를 확인해 주세요."); const draft = await response.json() as Detail; const detailResponse = await fetch(`/api/admin/settlements/${draft.id}`, { credentials: "same-origin" }); setDetail(detailResponse.ok ? { ...draft, ...(await detailResponse.json() as Detail) } : draft); setMessage("정산 초안을 만들었습니다. 근거 행을 검토한 뒤 마감할 수 있습니다.") }
  const finalize = async () => { if (!detail) return; const response = await fetch(`/api/admin/settlements/${detail.id}/finalize`, { method: "POST", credentials: "same-origin", headers: { "content-type": "application/json", "x-csrf-token": await csrf() }, body: JSON.stringify({ requestId: crypto.randomUUID() }) }); if (response.ok) { const result = await response.json() as { status: string; dueDate: string }; setDetail({ ...detail, ...result }); setMessage(`정산을 마감했습니다. 지급 기한은 ${result.dueDate}입니다.`) } else setMessage("정산을 마감하지 못했습니다.") }
  return <div className="space-y-6"><div><h1 className="text-2xl font-semibold tracking-tight">월 정산 초안</h1><p className="mt-1 text-sm text-muted-foreground">미정산 출고와 반품 차감 원장을 공급가액·세액 기준으로 고정합니다.</p></div>{message && <div className="rounded-md border bg-muted/50 px-4 py-3 text-sm">{message}</div>}<Card><CardContent className="pt-6"><form className="flex flex-col gap-3 md:flex-row md:items-end" onSubmit={create}><label className="grid flex-1 gap-2 text-sm font-medium">거래처<select className={selectClass} value={customerId} onChange={event => setCustomerId(event.target.value)} required><option value="">거래처 선택</option>{customers.map(customer => <option key={customer.id} value={customer.id}>{customer.code} · {customer.name}</option>)}</select></label><label className="grid gap-2 text-sm font-medium">정산월<Input type="month" value={period} onChange={event => setPeriod(event.target.value)} required /></label><Button type="submit" disabled={!customers.length}>초안 생성</Button></form></CardContent></Card>{detail && <Card><CardHeader><div className="flex items-center justify-between"><CardTitle>초안 근거 · {detail.id.slice(0, 8)}</CardTitle><Badge variant="secondary">{detail.status}</Badge></div><p className="text-sm text-muted-foreground">{detail.lineCount}건 · 공급가액 {won(detail.supplyAmount)} · 세액 {won(detail.taxAmount)} · 합계 {won(detail.totalAmount)}</p></CardHeader><CardContent className="space-y-4"><div className="divide-y rounded-md border">{detail.lines?.map(line => <div className="flex items-center justify-between gap-4 px-4 py-3 text-sm" key={line.id}><div><span className="text-xs text-muted-foreground">{String(line.businessDate).slice(0,10)} · {line.entryType === "shipment" ? "출고 청구" : "반품 차감"}</span><strong className="mt-1 block">{line.sku} · {line.productName}</strong></div><div className="text-right"><b>{won(line.amount)}</b><span className="block text-xs text-muted-foreground">공급 {won(line.supplyAmount)} · 세액 {won(line.taxAmount)}</span></div></div>)}</div>{detail.status === "draft" && <div className="flex justify-end"><Button onClick={finalize}>정산 마감</Button></div>}</CardContent></Card>}</div>
}
