import { BadRequestException, ConflictException, Inject, Injectable, OnModuleDestroy, OnModuleInit, ServiceUnavailableException } from '@nestjs/common';
import nodemailer,{Transporter} from 'nodemailer';
import { Pool } from 'pg';
import { API_CONFIG,ApiConfig } from '../config';
import { DATABASE } from '../database';

@Injectable()
export class NotificationService implements OnModuleInit,OnModuleDestroy{
  private readonly transport?:Transporter;private timer?:NodeJS.Timeout;private running=false;
  constructor(@Inject(DATABASE)private readonly pool:Pool,@Inject(API_CONFIG)private readonly config:ApiConfig){if(config.mail)this.transport=nodemailer.createTransport(config.mail.transport==='json'?{jsonTransport:true}:config.mail.smtpUrl!)}
  onModuleInit(){if(this.transport&&this.config.notificationWorkerEnabled){this.timer=setInterval(()=>void this.processDue(),15_000);this.timer.unref();void this.processDue()}}
  onModuleDestroy(){if(this.timer)clearInterval(this.timer)}
  async list(){try{return(await this.pool.query(`SELECT id,event_type AS "eventType",aggregate_type AS "aggregateType",aggregate_id AS "aggregateId",recipient_email AS recipient,subject,status,attempts,next_attempt_at AS "nextAttemptAt",sent_at AS "sentAt",last_error_code AS "lastErrorCode",created_at AS "createdAt" FROM notification_outbox ORDER BY created_at DESC,id DESC LIMIT 200`)).rows}catch{throw new ServiceUnavailableException('Notification outbox unavailable')}}
  async retry(id:string){if(!/^[0-9a-f-]{36}$/i.test(id))throw new BadRequestException('Invalid notification ID');try{const row=await this.pool.query("UPDATE notification_outbox SET status='pending',attempts=0,next_attempt_at=now(),locked_at=NULL,last_error_code=NULL,updated_at=now() WHERE id=$1 AND status='failed' RETURNING id,status",[id]);if(!row.rowCount)throw new ConflictException('Only failed notification can be retried');return row.rows[0]}catch(error){if(error instanceof BadRequestException||error instanceof ConflictException)throw error;throw new ServiceUnavailableException('Notification retry unavailable')}}
  async processDue(){if(!this.transport||this.running)return{processed:0};this.running=true;let processed=0;try{for(let index=0;index<20;index++){const db=await this.pool.connect();let item:any;try{await db.query('BEGIN');item=(await db.query(`SELECT * FROM notification_outbox WHERE ((status IN ('pending','failed') AND COALESCE(next_attempt_at,now())<=now()) OR (status='processing' AND locked_at<now()-interval '5 minutes')) AND attempts<8 ORDER BY created_at,id FOR UPDATE SKIP LOCKED LIMIT 1`)).rows[0];if(!item){await db.query('COMMIT');break}await db.query("UPDATE notification_outbox SET status='processing',attempts=attempts+1,locked_at=now(),updated_at=now() WHERE id=$1",[item.id]);await db.query('COMMIT')}catch(error){await db.query('ROLLBACK').catch(()=>{});throw error}finally{db.release()}try{const info=await this.transport.sendMail({from:this.config.mail!.from,to:item.recipient_email,subject:item.subject,text:item.body});await this.pool.query("UPDATE notification_outbox SET status='sent',sent_at=now(),provider_message_id=$2,locked_at=NULL,next_attempt_at=NULL,last_error_code=NULL,updated_at=now() WHERE id=$1",[item.id,info.messageId]);processed++}catch{const attempts=Number(item.attempts)+1;await this.pool.query(`UPDATE notification_outbox SET status='failed',locked_at=NULL,next_attempt_at=CASE WHEN $2>=8 THEN NULL ELSE now()+LEAST(interval '6 hours',interval '1 minute'*power(2,$2-1)) END,last_error_code='delivery_failed',updated_at=now() WHERE id=$1`,[item.id,attempts])}}return{processed}}finally{this.running=false}}
}
