'use client'

import { FormEvent, type ReactNode, useCallback, useEffect, useMemo, useState } from 'react'
import { CalendarDaysIcon, CheckCircle2Icon, CircleAlertIcon, PackageCheckIcon, RefreshCwIcon, SearchIcon, TruckIcon } from 'lucide-react'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { cn } from '@/lib/utils'
import { AttachmentPanel } from '@/components/attachment-panel'

type Status = 'ready'|'scheduled'|'in_transit'|'delivered'|'failed'
type Delivery = { shipmentId:string; orderId:string; shippedAt:string; customerName:string; customerCode:string; warehouseCode:string; status:Status; quantity:number; scheduledDate:string|null; carrierName:string|null; trackingNumber:string|null; dispatchedAt:string|null; deliveredAt:string|null; recipientName:string|null; proofMethod:string|null; proofNote:string|null; failureReason:string|null }
const labels:Record<Status,string>={ready:'배송 준비',scheduled:'배송 예정',in_transit:'배송 중',delivered:'인도 완료',failed:'배송 실패'}
const tones:Record<Status,string>={ready:'bg-slate-100 text-slate-700',scheduled:'bg-blue-50 text-blue-700',in_transit:'bg-amber-50 text-amber-800',delivered:'bg-emerald-50 text-emerald-700',failed:'bg-red-50 text-red-700'}
async function csrf(){const r=await fetch('/api/auth/csrf');if(!r.ok)throw new Error('보안 토큰을 준비하지 못했습니다.');return (await r.json()).csrfToken}

export default function DeliveryPage(){
 const [items,setItems]=useState<Delivery[]>([]),[selectedId,setSelectedId]=useState(''),[query,setQuery]=useState(''),[filter,setFilter]=useState<'all'|Status>('all'),[message,setMessage]=useState(''),[busy,setBusy]=useState(false)
 const load=useCallback(async()=>{const r=await fetch('/api/warehouse/deliveries');if(!r.ok){setMessage('배송 목록을 불러오지 못했습니다.');return}const rows=await r.json() as Delivery[];setItems(rows);setSelectedId(id=>rows.some(x=>x.shipmentId===id)?id:(rows[0]?.shipmentId??''))},[])
 useEffect(()=>{void load()},[load])
 const visible=useMemo(()=>items.filter(x=>(filter==='all'||x.status===filter)&&(!query.trim()||`${x.customerName} ${x.customerCode} ${x.trackingNumber??''} ${x.shipmentId}`.toLowerCase().includes(query.trim().toLowerCase()))),[items,filter,query])
 useEffect(()=>{if(visible.length&&!visible.some(x=>x.shipmentId===selectedId))setSelectedId(visible[0].shipmentId)},[visible,selectedId])
 const selected=items.find(x=>x.shipmentId===selectedId)??null
 const counts=(status:Status)=>items.filter(x=>x.status===status).length
 async function act(action:string,data:object){if(!selected)return;setBusy(true);setMessage('');try{const r=await fetch(`/api/warehouse/deliveries/${selected.shipmentId}/${action}`,{method:'POST',headers:{'content-type':'application/json','x-csrf-token':await csrf()},body:JSON.stringify({requestId:crypto.randomUUID(),...data})});if(!r.ok)throw new Error('현재 배송 상태와 입력값을 다시 확인해 주세요.');setMessage('배송 상태를 갱신했습니다.');await load()}catch(e){setMessage(e instanceof Error?e.message:'배송 처리에 실패했습니다.')}finally{setBusy(false)}}
 return <div className="space-y-5">
  <div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><h1 className="text-2xl font-semibold tracking-tight">배송 관리</h1><p className="mt-1 text-sm text-muted-foreground">출고 건별 배송 일정, 운송장, 인도 증빙을 한 흐름으로 관리합니다.</p></div><Button variant="outline" onClick={()=>void load()} disabled={busy}><RefreshCwIcon/>새로고침</Button></div>
  {message&&<div role="status" className="flex items-center gap-2 rounded-md border bg-muted/40 px-3 py-2 text-sm"><CircleAlertIcon className="size-4"/>{message}</div>}
  <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4" aria-label="배송 현황"><Metric icon={PackageCheckIcon} label="배송 준비" value={counts('ready')}/><Metric icon={CalendarDaysIcon} label="배송 예정" value={counts('scheduled')}/><Metric icon={TruckIcon} label="배송 중" value={counts('in_transit')}/><Metric icon={CheckCircle2Icon} label="인도 완료" value={counts('delivered')}/></section>
  <Card><CardContent className="flex flex-col gap-2 py-3 md:flex-row"><label className="relative flex-1"><SearchIcon className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground"/><Input className="pl-9" aria-label="배송 검색" value={query} onChange={e=>setQuery(e.target.value)} placeholder="거래처, 출고번호, 운송장 검색"/></label><div className="flex flex-wrap gap-1">{(['all','ready','scheduled','in_transit','delivered','failed'] as const).map(x=><Button key={x} size="sm" variant={filter===x?'default':'ghost'} onClick={()=>setFilter(x)}>{x==='all'?'전체':labels[x]} {x==='all'?items.length:counts(x)}</Button>)}</div></CardContent></Card>
  <div className="grid items-start gap-4 xl:grid-cols-[360px_minmax(0,1fr)]"><Card className="xl:sticky xl:top-20"><CardHeader className="border-b"><CardTitle>출고별 배송 목록</CardTitle><CardDescription>검색 결과 {visible.length}건</CardDescription></CardHeader><CardContent className="max-h-[680px] overflow-y-auto p-0">{visible.map(x=><button type="button" key={x.shipmentId} onClick={()=>setSelectedId(x.shipmentId)} className={cn('w-full border-b px-4 py-3 text-left hover:bg-muted/50',selectedId===x.shipmentId&&'bg-muted')}><div className="flex justify-between gap-2"><strong className="truncate text-sm">{x.customerName}</strong><StatusBadge status={x.status}/></div><p className="mt-1 font-mono text-[11px] text-muted-foreground">#{x.shipmentId.slice(0,8).toUpperCase()}</p><div className="mt-2 flex justify-between text-xs"><span>{x.quantity}개 · {x.warehouseCode}</span><span className="text-muted-foreground">{x.trackingNumber??'운송장 미등록'}</span></div></button>)}{!visible.length&&<p className="py-14 text-center text-sm text-muted-foreground">조건에 맞는 배송이 없습니다.</p>}</CardContent></Card>
  {selected?<DeliveryDetail item={selected} busy={busy} act={act}/>:<Card><CardContent className="grid min-h-72 place-items-center text-sm text-muted-foreground">배송 건을 선택해 주세요.</CardContent></Card>}</div>
 </div>
}

function DeliveryDetail({item,busy,act}:{item:Delivery;busy:boolean;act:(a:string,d:object)=>Promise<void>}){return <Card><CardHeader className="border-b"><div className="flex flex-col gap-3 sm:flex-row sm:justify-between"><div><div className="mb-2 flex gap-2"><StatusBadge status={item.status}/><span className="font-mono text-xs text-muted-foreground">#{item.shipmentId.slice(0,8).toUpperCase()}</span></div><CardTitle className="text-lg">{item.customerName}</CardTitle><CardDescription>{item.customerCode} · 주문 #{item.orderId.slice(0,8).toUpperCase()}</CardDescription></div><div className="grid grid-cols-2 gap-x-4 text-xs sm:text-right"><span className="text-muted-foreground">출고 창고</span><b>{item.warehouseCode}</b><span className="text-muted-foreground">출고 수량</span><b>{item.quantity}개</b></div></div></CardHeader><CardContent className="space-y-5"><div className="grid gap-2 sm:grid-cols-3"><Info label="출고 완료" value={new Date(item.shippedAt).toLocaleString('ko-KR')}/><Info label="배송 예정" value={item.scheduledDate??'미정'}/><Info label="운송장" value={item.trackingNumber?`${item.carrierName} · ${item.trackingNumber}`:'미등록'}/></div><Timeline status={item.status}/>{['ready','scheduled','failed'].includes(item.status)&&<ScheduleForm item={item} busy={busy} act={act}/>} {item.status==='scheduled'&&<Action title="배송 출발 처리" text="택배사 인계 후 배송 중 상태로 전환합니다."><Button onClick={()=>void act('dispatch',{})} disabled={busy}><TruckIcon/>배송 출발</Button></Action>}{item.status==='in_transit'&&<TransitForms busy={busy} act={act}/>} {item.status==='delivered'&&<div className="rounded-lg border border-emerald-200 bg-emerald-50/60 p-4"><strong className="text-sm text-emerald-800">인도 완료 증빙</strong><dl className="mt-3 grid gap-2 text-sm sm:grid-cols-2"><dt className="text-muted-foreground">수령인</dt><dd className="font-medium">{item.recipientName}</dd><dt className="text-muted-foreground">확인 내용</dt><dd className="font-medium">{item.proofNote}</dd></dl></div>}<AttachmentPanel resourceType="shipment" resourceId={item.shipmentId} canUpload /></CardContent></Card>}
function ScheduleForm({item,busy,act}:{item:Delivery;busy:boolean;act:(a:string,d:object)=>Promise<void>}){return <form className="rounded-lg border p-4" onSubmit={(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);void act('schedule',{scheduledDate:f.get('date'),carrierName:f.get('carrier'),trackingNumber:f.get('tracking')})}}><div className="mb-3"><strong className="text-sm">배송 일정과 운송장</strong><p className="text-xs text-muted-foreground">출발 전까지 변경할 수 있으며 변경 이력이 보존됩니다.</p></div><div className="grid gap-3 md:grid-cols-3"><Field label="배송 예정일"><Input name="date" type="date" defaultValue={item.scheduledDate??''} required/></Field><Field label="택배사"><Input name="carrier" defaultValue={item.carrierName??''} required/></Field><Field label="운송장 번호"><Input name="tracking" defaultValue={item.trackingNumber??''} required/></Field></div><div className="mt-3 flex justify-end"><Button disabled={busy}>{item.status==='failed'?'재배송 예약':'배송 일정 저장'}</Button></div></form>}
function TransitForms({busy,act}:{busy:boolean;act:(a:string,d:object)=>Promise<void>}){return <div className="grid gap-3 lg:grid-cols-2"><form className="rounded-lg border border-emerald-200 p-4" onSubmit={(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);void act('deliver',{recipientName:f.get('recipient'),proofMethod:f.get('method'),proofNote:f.get('note')})}}><strong className="text-sm">인도 완료</strong><div className="mt-3 grid gap-3"><Field label="수령인"><Input name="recipient" required/></Field><Field label="확인 방식"><select name="method" className="h-9 rounded-md border bg-background px-3 text-sm"><option value="staff_confirmation">직원 확인</option><option value="signature">서명 확인</option><option value="photo">사진 확인</option></select></Field><Field label="증빙 메모"><Input name="note" required/></Field><Button disabled={busy}>인도 완료 저장</Button></div></form><form className="rounded-lg border border-red-200 p-4" onSubmit={(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();void act('fail',{reason:new FormData(e.currentTarget).get('reason')})}}><strong className="text-sm text-red-700">배송 실패</strong><p className="mt-1 text-xs text-muted-foreground">주소 오류·수령 거부 등 재배송이 필요한 사유를 기록합니다.</p><div className="mt-3 grid gap-3"><Field label="실패 사유"><Input name="reason" required/></Field><Button variant="destructive" disabled={busy}>배송 실패 기록</Button></div></form></div>}
function Metric({icon:Icon,label,value}:{icon:typeof TruckIcon;label:string;value:number}){return <Card size="sm"><CardHeader className="grid grid-cols-[1fr_auto]"><CardDescription>{label}</CardDescription><span className="row-span-2 grid size-8 place-items-center rounded-md bg-muted"><Icon className="size-4"/></span><CardTitle className="text-2xl tabular-nums">{value}<span className="ml-1 text-sm font-normal text-muted-foreground">건</span></CardTitle></CardHeader></Card>}
function StatusBadge({status}:{status:Status}){return <Badge variant="secondary" className={tones[status]}>{labels[status]}</Badge>}
function Info({label,value}:{label:string;value:string}){return <div className="rounded-lg bg-muted/50 p-3"><span className="text-xs text-muted-foreground">{label}</span><strong className="mt-1 block text-sm">{value}</strong></div>}
function Field({label,children}:{label:string;children:ReactNode}){return <label className="grid gap-1.5 text-xs font-medium">{label}{children}</label>}
function Action({title,text,children}:{title:string;text:string;children:ReactNode}){return <div className="flex flex-col gap-3 rounded-lg border p-4 sm:flex-row sm:items-center"><div className="flex-1"><strong className="text-sm">{title}</strong><p className="text-xs text-muted-foreground">{text}</p></div>{children}</div>}
function Timeline({status}:{status:Status}){const steps=[['ready','출고 완료'],['scheduled','배송 예정'],['in_transit','배송 중'],['delivered','인도 완료']] as const;const active=status==='failed'?2:steps.findIndex(x=>x[0]===status);return <div className="grid grid-cols-4 gap-1">{steps.map(([key,text],i)=><div key={key} className="text-center"><div className={cn('h-1.5 rounded-full',i<=active?'bg-primary':'bg-muted')}/><span className="mt-1.5 block text-[11px] text-muted-foreground">{text}</span></div>)}</div>}
