"use client"
import { FormEvent, useCallback, useEffect, useState } from "react"
import { RecoveryCodeCard } from "@/components/security/recovery-code-card"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Textarea } from "@/components/ui/textarea"

type Account={id:string;email:string;roles:string[];confirmedAt:string}; type Me={id:string}
async function csrf(){return(await(await fetch("/api/auth/csrf",{credentials:"same-origin"})).json()as{csrfToken:string}).csrfToken}
export default function AccountSecurityPage(){
  const[accounts,setAccounts]=useState<Account[]>([]),[me,setMe]=useState<Me|null>(null),[selected,setSelected]=useState<Account|null>(null),[reason,setReason]=useState(""),[confirmed,setConfirmed]=useState(false),[message,setMessage]=useState("")
  const load=useCallback(async()=>{const[a,m]=await Promise.all([fetch("/api/auth/users/mfa-enrolled",{credentials:"same-origin"}),fetch("/api/auth/me",{credentials:"same-origin"})]);if(!a.ok||!m.ok)return setMessage("system 권한과 MFA 인증을 확인해 주세요.");setAccounts(await a.json()as Account[]);setMe(await m.json()as Me)},[])
  useEffect(()=>{void load()},[load])
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!selected||!confirmed)return;const response=await fetch(`/api/auth/users/${selected.id}/mfa-reset`,{method:"POST",credentials:"same-origin",headers:{"content-type":"application/json","x-csrf-token":await csrf()},body:JSON.stringify({requestId:crypto.randomUUID(),reason})});if(!response.ok)return setMessage("MFA 초기화에 실패했습니다. 대상 상태와 권한을 다시 확인해 주세요.");setMessage(`${selected.email} 계정의 세션과 복구 코드를 폐기했습니다.`);setSelected(null);setReason("");setConfirmed(false);await load()}
  return <div className="space-y-6"><div><h1 className="text-2xl font-semibold tracking-tight">계정 보안</h1><p className="mt-1 text-sm text-muted-foreground">복구 코드를 재발급하거나 승인된 계정의 MFA 등록을 초기화합니다.</p></div>{message&&<div role="status" className="rounded-md border bg-muted/50 px-4 py-3 text-sm">{message}</div>}<RecoveryCodeCard/><Card><CardHeader><CardTitle>MFA 등록 계정</CardTitle><CardDescription>초기화하면 모든 로그인 세션, TOTP 비밀값, 복구 코드가 즉시 폐기됩니다.</CardDescription></CardHeader><CardContent className="p-0"><div className="divide-y">{accounts.map(account=><div className="flex flex-col gap-3 px-6 py-4 sm:flex-row sm:items-center" key={account.id}><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><strong className="truncate text-sm">{account.email}</strong>{account.roles.map(role=><Badge variant="secondary" key={role}>{role}</Badge>)}</div><p className="mt-1 text-xs text-muted-foreground">등록 {new Date(account.confirmedAt).toLocaleString("ko-KR")}</p></div><Button variant="outline" disabled={account.id===me?.id} onClick={()=>{setSelected(account);setMessage("")}}>초기화 대상 선택</Button></div>)}{!accounts.length&&<p className="px-6 py-12 text-center text-sm text-muted-foreground">등록된 MFA 계정이 없습니다.</p>}</div></CardContent></Card>{selected&&<Card className="border-destructive/30"><CardHeader><CardTitle>{selected.email} MFA 초기화</CardTitle><CardDescription>승인된 사유를 기록하고 폐기 범위를 확인하세요.</CardDescription></CardHeader><CardContent><form className="grid gap-4" onSubmit={submit}><label className="grid gap-2 text-sm font-medium">초기화 사유<Textarea value={reason} onChange={event=>setReason(event.target.value)} minLength={4} maxLength={300} required/></label><label className="flex items-start gap-2 text-sm"><input className="mt-1" type="checkbox" checked={confirmed} onChange={event=>setConfirmed(event.target.checked)}/><span>기존 세션과 복구 코드가 모두 폐기됨을 확인했습니다.</span></label><div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={()=>setSelected(null)}>취소</Button><Button type="submit" variant="destructive" disabled={!confirmed||reason.trim().length<4}>MFA 초기화</Button></div></form></CardContent></Card>}</div>
}
