'use client'

import { FormEvent, useCallback, useEffect, useState } from 'react'
import { PackageCheckIcon, RefreshCwIcon, SearchIcon, Trash2Icon } from 'lucide-react'
import { AdminAnalyticsPanel } from '@/components/analytics/admin-analytics'
import { OrderPagination, type PageMetadata } from '@/components/orders/order-pagination'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'

type Item={inspectionId:string;customerCode:string;customerName:string;sku:string;productName:string;inspectedQuantity:number;normalQuantity:number;defectiveQuantity:number;unassignedDefectiveQuantity:number;defectiveReason:string|null;originalUnitPrice:string}
type Quarantine={dispositionId:string;quantity:number;reason:string;quarantinedAt:string;inspectionId:string;customerCode:string;customerName:string;sku:string;productName:string;resolvedQuantity:number;remainingQuantity:number}
type Supplier={id:string;code:string;name:string}
type ResolutionInput={quantity:string;supplierId:string;reference:string;reason:string}
async function csrf(){const response=await fetch('/api/auth/csrf',{credentials:'same-origin'});if(!response.ok)throw new Error('보안 토큰을 준비하지 못했습니다.');return(await response.json() as {csrfToken:string}).csrfToken}
async function post(path:string,body:object){return fetch(path,{method:'POST',credentials:'same-origin',headers:{'content-type':'application/json','x-csrf-token':await csrf()},body:JSON.stringify({requestId:crypto.randomUUID(),...body})})}

export default function ReturnCreditsPage(){
  const[items,setItems]=useState<Item[]>([]),[quarantines,setQuarantines]=useState<Quarantine[]>([]),[suppliers,setSuppliers]=useState<Supplier[]>([]),[quantities,setQuantities]=useState<Record<string,string>>({}),[resolutions,setResolutions]=useState<Record<string,ResolutionInput>>({}),[message,setMessage]=useState(''),[busy,setBusy]=useState(''),[loading,setLoading]=useState(true),[search,setSearch]=useState(''),[appliedSearch,setAppliedSearch]=useState(''),[page,setPage]=useState(1),[metadata,setMetadata]=useState<PageMetadata>({page:1,pageSize:50,total:0,totalPages:0})
  const load=useCallback(async()=>{setLoading(true);const parameters=new URLSearchParams({page:String(page),pageSize:'50'});if(appliedSearch)parameters.set('query',appliedSearch);const[itemResponse,quarantineResponse,catalogResponse]=await Promise.all([fetch(`/api/admin/returns/credits/pending?${parameters}`,{credentials:'same-origin'}),fetch('/api/admin/returns/defects/quarantined',{credentials:'same-origin'}),fetch('/api/admin/catalog',{credentials:'same-origin'})]);if(!itemResponse.ok||!quarantineResponse.ok||!catalogResponse.ok){setMessage('반품 처리 정보를 불러오지 못했습니다.');setLoading(false);return}const result=await itemResponse.json() as PageMetadata&{items:Item[]};if(result.totalPages>0&&page>result.totalPages){setPage(result.totalPages);return}setItems(result.items);setMetadata(result);setQuarantines(await quarantineResponse.json() as Quarantine[]);setSuppliers((await catalogResponse.json() as {suppliers:Supplier[]}).suppliers);setLoading(false)},[appliedSearch,page])
  useEffect(()=>{void load()},[load]);useEffect(()=>{const timer=setTimeout(()=>{setAppliedSearch(search.trim());setPage(1)},300);return()=>clearTimeout(timer)},[search])
  async function credit(event:FormEvent<HTMLFormElement>,item:Item){event.preventDefault();setBusy(item.inspectionId);const response=await post(`/api/admin/returns/inspections/${item.inspectionId}/credit`,{quantity:Number(quantities[item.inspectionId]||item.inspectedQuantity)});setMessage(response.ok?'반품 차감액을 확정했습니다.':'반품 차감액을 확정하지 못했습니다.');if(response.ok)await load();setBusy('')}
  async function disposeOrHold(item:Item,disposition:'quarantine'|'disposed'){if(item.unassignedDefectiveQuantity<1)return;setBusy(item.inspectionId);const response=await post(`/api/admin/returns/inspections/${item.inspectionId}/defects`,{quantity:item.unassignedDefectiveQuantity,disposition,reason:disposition==='quarantine'?'공급처 확인 전 품질 격리':'승인된 자체 폐기'});setMessage(response.ok?(disposition==='quarantine'?'불량 수량을 격리했습니다.':'불량 수량을 폐기했습니다.'):'불량 수량을 처리하지 못했습니다.');if(response.ok)await load();setBusy('')}
  const update=(id:string,key:keyof ResolutionInput,value:string)=>setResolutions(current=>{const previous=current[id]??{quantity:String(quarantines.find(item=>item.dispositionId===id)?.remainingQuantity??''),supplierId:'',reference:'',reason:''};return{...current,[id]:{...previous,[key]:value}}})
  async function resolve(item:Quarantine,resolution:'supplier_return'|'disposed'){const value=resolutions[item.dispositionId]??{quantity:String(item.remainingQuantity),supplierId:'',reference:'',reason:''};setBusy(item.dispositionId);const response=await post(`/api/admin/returns/defects/${item.dispositionId}/resolve`,{quantity:Number(value.quantity||item.remainingQuantity),resolution,supplierId:resolution==='supplier_return'?value.supplierId:undefined,reference:resolution==='supplier_return'?value.reference:undefined,reason:value.reason|| (resolution==='disposed'?'격리 후 폐기 승인':'공급처 반송 인계')});setMessage(response.ok?(resolution==='disposed'?'격리품을 폐기 완료 처리했습니다.':'격리품의 공급처 반환을 기록했습니다.'):'격리품을 해결하지 못했습니다. 공급처와 참조번호를 확인해 주세요.');if(response.ok)await load();setBusy('')}
  return <div className="space-y-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><h1 className="text-2xl font-semibold tracking-tight">반품 차감 · 불량 처리</h1><p className="mt-1 text-sm text-muted-foreground">반품 금액을 확정하고 불량품의 격리부터 공급처 반환·폐기까지 추적합니다.</p></div><Button variant="outline" onClick={()=>void load()} disabled={loading}><RefreshCwIcon className={loading?'animate-spin':''}/>새로고침</Button></div>
  {message&&<div role="status" className="rounded-md border bg-muted/50 px-4 py-3 text-sm">{message}</div>}<AdminAnalyticsPanel view="returns"/>
  <Card><CardContent className="py-3"><label className="relative block"><SearchIcon className="pointer-events-none absolute left-2.5 top-1/2 size-4 -translate-y-1/2 text-muted-foreground"/><Input className="pl-8" value={search} onChange={event=>setSearch(event.target.value)} placeholder="거래처, SKU, 상품명, 불량 사유 검색" aria-label="반품 차감 검색"/></label></CardContent></Card>
  <section className="space-y-3"><div><h2 className="text-lg font-semibold">금액 차감 대기</h2><p className="text-sm text-muted-foreground">검수 수량과 원출고 단가를 기준으로 차감액을 확정합니다.</p></div><OrderPagination metadata={metadata} loading={loading} onPageChange={setPage}/><div className="grid gap-4 xl:grid-cols-2">{items.map(item=><Card key={item.inspectionId}><CardHeader><div className="flex items-start justify-between gap-3"><div><CardTitle>{item.sku} · {item.productName}</CardTitle><CardDescription>{item.customerCode} · {item.customerName}</CardDescription></div><Badge variant={item.defectiveQuantity?'destructive':'secondary'}>불량 {item.defectiveQuantity}</Badge></div></CardHeader><CardContent className="space-y-4"><form className="grid gap-4" onSubmit={event=>void credit(event,item)}><div className="grid grid-cols-3 rounded-md border bg-muted/30 text-center text-sm"><Stat label="검수" value={item.inspectedQuantity}/><Stat label="정상" value={item.normalQuantity} border/><Stat label="원출고 단가" value={`${Number(item.originalUnitPrice).toLocaleString('ko-KR')}원`}/></div>{item.defectiveReason&&<p className="text-sm text-destructive">불량 사유: {item.defectiveReason}</p>}<label className="grid gap-2 text-sm font-medium">차감 수량<Input type="number" min="1" max={item.inspectedQuantity} value={quantities[item.inspectionId]||String(item.inspectedQuantity)} onChange={event=>setQuantities(current=>({...current,[item.inspectionId]:event.target.value}))}/></label><Button disabled={busy===item.inspectionId}>차감 확정</Button></form>{item.unassignedDefectiveQuantity>0&&<div className="grid grid-cols-2 gap-2 border-t pt-4"><Button type="button" variant="outline" disabled={busy===item.inspectionId} onClick={()=>void disposeOrHold(item,'quarantine')}>불량 격리 {item.unassignedDefectiveQuantity}</Button><Button type="button" variant="destructive" disabled={busy===item.inspectionId} onClick={()=>void disposeOrHold(item,'disposed')}>즉시 폐기</Button></div>}</CardContent></Card>)}{!items.length&&<Empty text="조건에 맞는 차감 대기 반품이 없습니다."/>}</div></section>
  <section className="space-y-3"><div><h2 className="text-lg font-semibold">격리품 해결 대기</h2><p className="text-sm text-muted-foreground">격리된 불량품을 공급처에 반환하거나 승인된 절차로 폐기합니다.</p></div><div className="grid gap-4 xl:grid-cols-2">{quarantines.map(item=>{const value=resolutions[item.dispositionId]??{quantity:String(item.remainingQuantity),supplierId:'',reference:'',reason:''};return <Card key={item.dispositionId}><CardHeader><div className="flex items-start justify-between gap-3"><div><CardTitle>{item.sku} · {item.productName}</CardTitle><CardDescription>{item.customerCode} · {item.customerName} · 격리 사유 {item.reason}</CardDescription></div><Badge variant="outline">잔여 {item.remainingQuantity}</Badge></div></CardHeader><CardContent className="grid gap-3"><div className="grid gap-3 sm:grid-cols-2"><label className="grid gap-1.5 text-xs font-medium">처리 수량<Input type="number" min="1" max={item.remainingQuantity} value={value.quantity} onChange={event=>update(item.dispositionId,'quantity',event.target.value)}/></label><label className="grid gap-1.5 text-xs font-medium">공급처<select className="h-9 rounded-md border bg-transparent px-3 text-sm" value={value.supplierId} onChange={event=>update(item.dispositionId,'supplierId',event.target.value)}><option value="">공급처 선택</option>{suppliers.map(supplier=><option key={supplier.id} value={supplier.id}>{supplier.code} · {supplier.name}</option>)}</select></label></div><label className="grid gap-1.5 text-xs font-medium">반송 참조번호<Input value={value.reference} onChange={event=>update(item.dispositionId,'reference',event.target.value)} placeholder="택배 운송장 또는 공급처 접수번호"/></label><label className="grid gap-1.5 text-xs font-medium">처리 사유<Input value={value.reason} onChange={event=>update(item.dispositionId,'reason',event.target.value)} placeholder="승인 근거와 인계 내용"/></label><div className="grid grid-cols-2 gap-2"><Button variant="outline" disabled={busy===item.dispositionId||!value.supplierId||!value.reference} onClick={()=>void resolve(item,'supplier_return')}><PackageCheckIcon/>공급처 반환</Button><Button variant="destructive" disabled={busy===item.dispositionId} onClick={()=>void resolve(item,'disposed')}><Trash2Icon/>격리품 폐기</Button></div></CardContent></Card>})}{!quarantines.length&&<Empty text="해결 대기 중인 격리품이 없습니다."/>}</div></section></div>
}

function Stat({label,value,border=false}:{label:string;value:string|number;border?:boolean}){return <div className={`p-3 ${border?'border-x':''}`}><span className="block text-xs text-muted-foreground">{label}</span><b>{value}</b></div>}
function Empty({text}:{text:string}){return <div className="col-span-full rounded-lg border border-dashed py-14 text-center text-sm text-muted-foreground">{text}</div>}
