'use client'

import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react'
import { Bar, BarChart, CartesianGrid, XAxis, YAxis } from 'recharts'
import { HandCoinsIcon, RefreshCwIcon, WalletCardsIcon } from 'lucide-react'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { ChartContainer, ChartTooltip, ChartTooltipContent, type ChartConfig } from '@/components/ui/chart'
import { Input } from '@/components/ui/input'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table'

type Source={sourceType:'payment'|'return_credit';sourceId:string;customerId:string;customerCode:string;customerName:string;sourceDate:string;sourceLabel:string;amount:string;availableAmount:string}
type Refund={id:string;customerCode:string;customerName:string;sourceType:'payment'|'return_credit';refundDate:string;amount:string;method:string;reference:string;reason:string;recordedAt:string;recordedBy:string}
const chartConfig={amount:{label:'환불액',color:'#2563eb'}} satisfies ChartConfig
const won=(value:string|number)=>`${Number(value).toLocaleString('ko-KR')}원`
async function csrf(){const response=await fetch('/api/auth/csrf',{credentials:'same-origin'});if(!response.ok)throw new Error('보안 토큰을 준비하지 못했습니다.');return(await response.json() as {csrfToken:string}).csrfToken}

export default function RefundsPage(){
  const[sources,setSources]=useState<Source[]>([]),[refunds,setRefunds]=useState<Refund[]>([]),[selectedKey,setSelectedKey]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true)
  const load=useCallback(async()=>{setLoading(true);const[sourceResponse,refundResponse]=await Promise.all([fetch('/api/admin/refunds/sources',{credentials:'same-origin'}),fetch('/api/admin/refunds',{credentials:'same-origin'})]);if(!sourceResponse.ok||!refundResponse.ok){setMessage('환불 원천과 이력을 불러오지 못했습니다.');setLoading(false);return}const nextSources=await sourceResponse.json() as Source[];setSources(nextSources);setRefunds(await refundResponse.json() as Refund[]);setSelectedKey(current=>nextSources.some(item=>key(item)===current)?current:(nextSources[0]?key(nextSources[0]):''));setLoading(false)},[])
  useEffect(()=>{void load()},[load])
  const selected=sources.find(item=>key(item)===selectedKey),total=refunds.reduce((sum,item)=>sum+Number(item.amount),0),available=sources.reduce((sum,item)=>sum+Number(item.availableAmount),0)
  const chartData=useMemo(()=>refunds.slice(0,10).reverse().map(item=>({label:item.reference.slice(0,12),amount:Number(item.amount)})),[refunds])
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!selected)return;const formElement=event.currentTarget,form=new FormData(formElement);setBusy(true);setMessage('');try{const response=await fetch('/api/admin/refunds',{method:'POST',credentials:'same-origin',headers:{'content-type':'application/json','x-csrf-token':await csrf()},body:JSON.stringify({requestId:crypto.randomUUID(),sourceType:selected.sourceType,sourceId:selected.sourceId,refundDate:form.get('refundDate'),amount:Number(form.get('amount')),method:form.get('method'),reference:form.get('reference'),reason:form.get('reason')})});const result=await response.json().catch(()=>({})) as {message?:string};if(!response.ok)throw new Error(result.message??'환불을 기록하지 못했습니다.');formElement.reset();setMessage('실제 송금이 완료된 환불 기록을 저장했습니다.');await load()}catch(error){setMessage(error instanceof Error?error.message:'환불 처리 중 오류가 발생했습니다.')}finally{setBusy(false)}}
  return <div className="space-y-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><h1 className="text-2xl font-semibold tracking-tight">실제 환불</h1><p className="mt-1 text-sm text-muted-foreground">미배분 입금이나 반품 차감 잔액에서 실제 송금이 끝난 환불을 기록합니다.</p></div><Button variant="outline" onClick={()=>void load()} disabled={loading}><RefreshCwIcon className={loading?'animate-spin':''}/>새로고침</Button></div>
  {message&&<div role="status" className="rounded-md border bg-muted/40 px-4 py-3 text-sm">{message}</div>}
  <section className="grid gap-3 sm:grid-cols-3"><Metric label="환불 가능 잔액" value={won(available)} icon={WalletCardsIcon}/><Metric label="누적 환불" value={won(total)} icon={HandCoinsIcon}/><Metric label="환불 기록" value={`${refunds.length.toLocaleString('ko-KR')}건`} icon={RefreshCwIcon}/></section>
  <div className="grid items-start gap-4 xl:grid-cols-[380px_minmax(0,1fr)]"><Card><CardHeader className="border-b"><CardTitle>환불 원천</CardTitle><CardDescription>사용 가능한 금액 범위에서 원천을 선택합니다.</CardDescription></CardHeader><CardContent className="max-h-[620px] overflow-y-auto p-0">{sources.map(item=><button key={key(item)} type="button" onClick={()=>setSelectedKey(key(item))} className={`w-full border-b px-4 py-3 text-left hover:bg-muted/50 ${key(item)===selectedKey?'bg-muted':''}`}><div className="flex items-start justify-between gap-2"><div><strong className="text-sm">{item.customerName}</strong><p className="mt-1 text-xs text-muted-foreground">{item.customerCode} · {item.sourceLabel}</p></div><Badge variant="outline">{item.sourceType==='payment'?'미배분 입금':'반품 차감'}</Badge></div><p className="mt-3 text-sm">환불 가능 <b className="float-right tabular-nums">{won(item.availableAmount)}</b></p></button>)}{!sources.length&&<p className="py-14 text-center text-sm text-muted-foreground">환불 가능한 원천이 없습니다.</p>}</CardContent></Card>
  <Card><CardHeader className="border-b"><CardTitle>{selected?`${selected.customerName} 환불 기록`:'환불 원천을 선택하세요'}</CardTitle>{selected&&<CardDescription>{selected.sourceLabel} · 원금 {won(selected.amount)} · 가능 {won(selected.availableAmount)}</CardDescription>}</CardHeader><CardContent>{selected?<form className="grid gap-4" onSubmit={submit}><div className="grid gap-3 sm:grid-cols-3"><label className="grid gap-1.5 text-xs font-medium">환불일<Input name="refundDate" type="date" required/></label><label className="grid gap-1.5 text-xs font-medium">환불액<Input name="amount" type="number" min="1" max={selected.availableAmount} required/></label><label className="grid gap-1.5 text-xs font-medium">방법<select name="method" required className="h-9 rounded-md border bg-transparent px-3 text-sm"><option value="bank_transfer">계좌 이체</option><option value="card_reversal">카드 취소</option><option value="cash">현금</option><option value="other">기타</option></select></label></div><label className="grid gap-1.5 text-xs font-medium">송금·승인 참조번호<Input name="reference" maxLength={120} required placeholder="예: RF-20260909-001"/></label><label className="grid gap-1.5 text-xs font-medium">환불 사유<Input name="reason" maxLength={300} required placeholder="초과 입금 반환 또는 반품 차감액 환불"/></label><div className="flex justify-end"><Button disabled={busy}><HandCoinsIcon/>{busy?'저장 중…':'환불 기록 저장'}</Button></div></form>:<p className="py-14 text-center text-sm text-muted-foreground">왼쪽에서 환불 원천을 선택하세요.</p>}</CardContent></Card></div>
  <div className="grid gap-4 xl:grid-cols-[0.8fr_1.2fr]"><Card><CardHeader><CardTitle>최근 환불 규모</CardTitle><CardDescription>최근 10건의 실제 환불액입니다.</CardDescription></CardHeader><CardContent>{chartData.length?<ChartContainer config={chartConfig} className="h-56 w-full"><BarChart data={chartData} accessibilityLayer><CartesianGrid vertical={false}/><XAxis dataKey="label"/><YAxis tickFormatter={value=>`${Math.round(Number(value)/10000)}만`}/><ChartTooltip content={<ChartTooltipContent/>}/><Bar dataKey="amount" fill="var(--color-amount)" radius={3}/></BarChart></ChartContainer>:<p className="grid h-56 place-items-center text-sm text-muted-foreground">환불 기록이 없습니다.</p>}</CardContent></Card><Card><CardHeader><CardTitle>환불 이력</CardTitle><CardDescription>원천, 송금 참조번호와 담당자를 추적합니다.</CardDescription></CardHeader><CardContent className="p-0"><div className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>환불일</TableHead><TableHead>거래처</TableHead><TableHead>원천</TableHead><TableHead>참조번호</TableHead><TableHead className="text-right">금액</TableHead></TableRow></TableHeader><TableBody>{refunds.map(item=><TableRow key={item.id}><TableCell className="whitespace-nowrap">{String(item.refundDate).slice(0,10)}</TableCell><TableCell><strong>{item.customerName}</strong><p className="text-xs text-muted-foreground">{item.reason}</p></TableCell><TableCell>{item.sourceType==='payment'?'입금':'반품 차감'}</TableCell><TableCell className="font-mono text-xs">{item.reference}</TableCell><TableCell className="text-right font-semibold tabular-nums">{won(item.amount)}</TableCell></TableRow>)}{!refunds.length&&<TableRow><TableCell colSpan={5} className="h-28 text-center text-muted-foreground">환불 기록이 없습니다.</TableCell></TableRow>}</TableBody></Table></div></CardContent></Card></div></div>
}

const key=(source:Source)=>`${source.sourceType}:${source.sourceId}`
function Metric({label,value,icon:Icon}:{label:string;value:string;icon:typeof HandCoinsIcon}){return <Card size="sm"><CardHeader className="grid grid-cols-[1fr_auto]"><CardDescription>{label}</CardDescription><span className="row-span-2 grid size-8 place-items-center rounded-md bg-muted"><Icon className="size-4"/></span><CardTitle className="text-xl tabular-nums">{value}</CardTitle></CardHeader></Card>}
