'use client'

import { useEffect, useState } from 'react'
import { CustomerAnalyticsPanel } from '@/components/analytics/role-analytics'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table'

type Entry={id:string;businessDate:string;entryType:'shipment'|'return_credit'|'refund';amount:string;productName:string|null}
type Payment={id:string;paymentDate:string;amount:string;allocatedAmount:string;refundedAmount:string;unallocatedAmount:string;status:string;reference:string}
type Refund={id:string;refundDate:string;amount:string;method:string;reference:string;reason:string;sourceType:'payment'|'return_credit'}
type Settlement={id:string;period:string;status:string;supplyAmount:string;taxAmount:string;totalAmount:string;allocatedAmount:string;dueDate:string|null}
type Statement=Settlement&{customerCode:string;customerName:string;paymentDueDay:number;lines:{id:string;businessDate:string;entryType:string;sku:string;productName:string;supplyAmount:string;taxAmount:string;amount:string}[]}
const won=(value:string|number)=>`${Number(value).toLocaleString('ko-KR')}원`
const entryLabel=(type:Entry['entryType'])=>type==='shipment'?'출고':type==='return_credit'?'반품 차감':'현금 환불 조정'

export default function PortalSettlements(){
  const[entries,setEntries]=useState<Entry[]>([]),[payments,setPayments]=useState<Payment[]>([]),[refunds,setRefunds]=useState<Refund[]>([]),[settlements,setSettlements]=useState<Settlement[]>([]),[statement,setStatement]=useState<Statement|null>(null),[message,setMessage]=useState('')
  useEffect(()=>{void Promise.all([fetch('/api/receivables',{credentials:'same-origin'}),fetch('/api/payments',{credentials:'same-origin'}),fetch('/api/refunds',{credentials:'same-origin'}),fetch('/api/settlements',{credentials:'same-origin'})]).then(async([receivables,paymentList,refundList,settlementList])=>{if(!receivables.ok||!paymentList.ok||!refundList.ok||!settlementList.ok)return setMessage('정산 정보를 불러오지 못했습니다.');setEntries(await receivables.json());setPayments(await paymentList.json());setRefunds(await refundList.json());setSettlements(await settlementList.json())})},[])
  const openStatement=async(id:string)=>{const response=await fetch(`/api/settlements/${id}`,{credentials:'same-origin'});if(response.ok)setStatement(await response.json());else setMessage('거래명세서를 불러오지 못했습니다.')}
  const total=entries.reduce((sum,entry)=>sum+Number(entry.amount),0)
  return <div className="space-y-6"><div><h1 className="text-2xl font-semibold tracking-tight">정산 · 입금 내역</h1><p className="mt-1 text-sm text-muted-foreground">출고, 반품 차감, 입금 배분과 실제 환불 내역을 확인합니다.</p></div>{message&&<div className="rounded-md border bg-muted/50 px-4 py-3 text-sm">{message}</div>}<CustomerAnalyticsPanel view="finance"/>
  <Card><CardHeader><p className="text-sm text-muted-foreground">현재 매출 원장 합계</p><CardTitle className="text-3xl tabular-nums">{won(total)}</CardTitle></CardHeader></Card>
  <Card><CardHeader><CardTitle>월 정산 · 거래명세서</CardTitle></CardHeader><CardContent className="divide-y rounded-md border p-0">{settlements.map(item=><div className="flex flex-col gap-3 px-4 py-3 sm:flex-row sm:items-center" key={item.id}><div className="flex-1"><strong className="text-sm">{item.period} 정산</strong><p className="text-xs text-muted-foreground">공급 {won(item.supplyAmount)} · 세액 {won(item.taxAmount)} · 지급 기한 {item.dueDate??'마감 전'}</p></div><b className="text-sm">{won(item.totalAmount)}</b><Button size="sm" variant="outline" onClick={()=>void openStatement(item.id)}>명세서 보기</Button></div>)}{!settlements.length&&<p className="py-10 text-center text-sm text-muted-foreground">마감된 정산이 없습니다.</p>}</CardContent></Card>
  {statement&&<Card><CardHeader><div className="flex items-center justify-between gap-3"><div><CardTitle>거래명세서 · {statement.period}</CardTitle><p className="mt-1 text-sm text-muted-foreground">{statement.customerCode} · {statement.customerName} · 지급 기한 {statement.dueDate??'마감 전'}</p></div><Button variant="outline" onClick={()=>window.print()}>인쇄</Button></div></CardHeader><CardContent><div className="mb-4 grid grid-cols-3 gap-2 rounded-md border p-4 text-sm"><span>공급가액 <b className="block">{won(statement.supplyAmount)}</b></span><span>부가세 <b className="block">{won(statement.taxAmount)}</b></span><span>합계 <b className="block">{won(statement.totalAmount)}</b></span></div><Table><TableHeader><TableRow><TableHead>일자</TableHead><TableHead>품목</TableHead><TableHead className="text-right">공급가액</TableHead><TableHead className="text-right">세액</TableHead><TableHead className="text-right">합계</TableHead></TableRow></TableHeader><TableBody>{statement.lines.map(line=><TableRow key={line.id}><TableCell>{String(line.businessDate).slice(0,10)}</TableCell><TableCell>{line.sku} · {line.productName}</TableCell><TableCell className="text-right">{won(line.supplyAmount)}</TableCell><TableCell className="text-right">{won(line.taxAmount)}</TableCell><TableCell className="text-right font-medium">{won(line.amount)}</TableCell></TableRow>)}</TableBody></Table></CardContent></Card>}
  <Card><CardHeader><CardTitle>매출 원장</CardTitle></CardHeader><CardContent className="p-0"><div className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>일자</TableHead><TableHead>구분</TableHead><TableHead>상품</TableHead><TableHead className="text-right">금액</TableHead></TableRow></TableHeader><TableBody>{entries.map(entry=><TableRow key={entry.id}><TableCell className="whitespace-nowrap">{String(entry.businessDate).slice(0,10)}</TableCell><TableCell><Badge variant="secondary">{entryLabel(entry.entryType)}</Badge></TableCell><TableCell>{entry.productName??'-'}</TableCell><TableCell className="text-right font-medium tabular-nums">{won(entry.amount)}</TableCell></TableRow>)}</TableBody></Table></div>{!entries.length&&<p className="py-12 text-center text-sm text-muted-foreground">표시할 원장 내역이 없습니다.</p>}</CardContent></Card>
  <div className="grid gap-4 xl:grid-cols-2"><Card><CardHeader><CardTitle>입금 현황</CardTitle></CardHeader><CardContent className="divide-y rounded-md border p-0">{payments.map(payment=><div className="flex items-center gap-4 px-4 py-3" key={payment.id}><div className="min-w-0 flex-1"><strong className="text-sm">{String(payment.paymentDate).slice(0,10)} · {payment.reference}</strong><p className="text-xs text-muted-foreground">배분 {won(payment.allocatedAmount)} · 환불 {won(payment.refundedAmount??'0')} · 미배분 {won(payment.unallocatedAmount)}</p></div><Badge variant="secondary">{payment.status==='voided'?'취소':'입금'}</Badge><b className="text-sm tabular-nums">{won(payment.amount)}</b></div>)}{!payments.length&&<p className="py-12 text-center text-sm text-muted-foreground">입금 내역이 없습니다.</p>}</CardContent></Card>
  <Card><CardHeader><CardTitle>실제 환불</CardTitle></CardHeader><CardContent className="divide-y rounded-md border p-0">{refunds.map(refund=><div className="px-4 py-3" key={refund.id}><div className="flex items-start justify-between gap-3"><div><strong className="text-sm">{String(refund.refundDate).slice(0,10)} · {refund.reference}</strong><p className="mt-1 text-xs text-muted-foreground">{refund.reason} · {refund.sourceType==='payment'?'초과 입금':'반품 차감'}</p></div><b className="whitespace-nowrap text-sm tabular-nums">{won(refund.amount)}</b></div></div>)}{!refunds.length&&<p className="py-12 text-center text-sm text-muted-foreground">환불 내역이 없습니다.</p>}</CardContent></Card></div></div>
}
