"use client"
import { FormEvent, useState } from "react"
import { CopyIcon, KeyRoundIcon } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"

async function csrf() { return (await (await fetch("/api/auth/csrf", { credentials: "same-origin" })).json() as { csrfToken: string }).csrfToken }
export function RecoveryCodeCard() {
  const [password,setPassword]=useState(""), [code,setCode]=useState(""), [confirmed,setConfirmed]=useState(false), [codes,setCodes]=useState<string[]>([]), [message,setMessage]=useState(""), [busy,setBusy]=useState(false)
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!confirmed)return;setBusy(true);setMessage("");const response=await fetch("/api/auth/mfa/recovery-codes",{method:"POST",credentials:"same-origin",headers:{"content-type":"application/json","x-csrf-token":await csrf()},body:JSON.stringify({password,code})});if(response.ok){setCodes((await response.json() as {recoveryCodes:string[]}).recoveryCodes);setPassword("");setCode("");setConfirmed(false);setMessage("새 복구 코드를 발급했습니다. 기존 코드는 모두 폐기되었습니다.")}else setMessage("재발급하지 못했습니다. 비밀번호와 새 인증 앱 코드를 확인해 주세요.");setBusy(false)}
  async function copy(){await navigator.clipboard.writeText(codes.join("\n"));setMessage("복구 코드 10개를 복사했습니다.")}
  return <Card><CardHeader><CardTitle className="flex items-center gap-2"><KeyRoundIcon className="size-4"/>내 복구 코드 재발급</CardTitle><CardDescription>현재 비밀번호와 아직 사용하지 않은 인증 앱 코드로 본인을 확인합니다.</CardDescription></CardHeader><CardContent>{codes.length?<div><div className="grid grid-cols-2 gap-2 rounded-md border bg-muted/40 p-4">{codes.map(value=><code className="text-xs" key={value}>{value}</code>)}</div><div className="mt-3 flex items-center justify-between gap-3"><p className="text-xs text-muted-foreground">이 화면을 닫으면 다시 확인할 수 없습니다.</p><Button onClick={()=>void copy()}><CopyIcon/>모두 복사</Button></div></div>:<form className="grid gap-3 sm:grid-cols-2" onSubmit={submit}><label className="grid gap-1.5 text-sm font-medium">현재 비밀번호<Input type="password" value={password} onChange={event=>setPassword(event.target.value)} required autoComplete="current-password"/></label><label className="grid gap-1.5 text-sm font-medium">6자리 인증 코드<Input inputMode="numeric" pattern="[0-9]{6}" maxLength={6} value={code} onChange={event=>setCode(event.target.value.replace(/\D/g,""))} required autoComplete="one-time-code"/></label><label className="flex items-start gap-2 text-sm sm:col-span-2"><input className="mt-1" type="checkbox" checked={confirmed} onChange={event=>setConfirmed(event.target.checked)}/><span>기존 복구 코드가 즉시 폐기됨을 확인했습니다.</span></label><div className="sm:col-span-2 sm:text-right"><Button type="submit" disabled={!confirmed||code.length!==6||busy}>{busy?"확인 중…":"새 복구 코드 발급"}</Button></div></form>}{message&&<p role="status" className="mt-3 text-sm text-muted-foreground">{message}</p>}</CardContent></Card>
}
